version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8014 --timeout 120 --workers 4
    restart: always
    volumes:
      - static_volume:/home/nesssery/coding-challenge/static
      - media_volume:/home/nesssery/coding-challenge/media
    ports:
      - 8014:8014
    expose:
      - 8014
    env_file:
      - ./.env
    networks:
      - nesssery

networks:
  nesssery:
    name: nesssery
    external: true

volumes:
  static_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/nesssery/Desktop/coding-challenge/static
  media_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/nesssery/Desktop/coding-challenge/media
