# Generated by Django 4.1.5 on 2023-11-05 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stores.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateAdded', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name="La date et l'heure d'ajout")),
                ('dateUpdated', models.DateTimeField(auto_now=True, null=True, verbose_name="La date et l'heure de mise à jour")),
            ],
            options={
                'verbose_name': 'Les badges',
                'verbose_name_plural': 'Les badges',
                'ordering': ('-dateAdded',),
            },
        ),
        migrations.CreateModel(
            name='Model3d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=stores.models.getModel3deFilepath, verbose_name="L'image 3D")),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('dateAdded', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name="La date et l'heure d'ajout")),
                ('dateUpdated', models.DateTimeField(auto_now=True, null=True, verbose_name="La date et l'heure de mise à jour")),
            ],
            options={
                'verbose_name': 'Les Model3d',
                'verbose_name_plural': 'Les Model3d',
                'ordering': ('-dateAdded',),
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name="La date et l'heure d'ajout")),
                ('dateUpdated', models.DateTimeField(auto_now=True, null=True, verbose_name="La date et l'heure de mise à jour")),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.badge')),
            ],
            options={
                'verbose_name': 'Les badges attribués',
                'verbose_name_plural': 'Les badges attribués',
                'ordering': ('-dateAdded',),
            },
        ),
    ]
